INSERT INTO accounts(NUMBER,AGENCY, BANK, TYPE_ACCOUNT ) VALUES (10, '10', '10', 'CONTA_CREDITO');
INSERT INTO accounts(NUMBER,AGENCY, BANK, TYPE_ACCOUNT ) VALUES (20, '20', '20', 'CONTA_CREDITO');
INSERT INTO accounts(NUMBER,AGENCY, BANK, TYPE_ACCOUNT ) VALUES (30, '30', '30', 'CONTA_CREDITO');
INSERT INTO accounts(NUMBER,AGENCY, BANK, TYPE_ACCOUNT ) VALUES (40, '40', '40', 'CONTA_CREDITO');
INSERT INTO accounts(NUMBER,AGENCY, BANK, TYPE_ACCOUNT ) VALUES (50, '40', '40', 'CONTA_CREDITO');
INSERT INTO accounts(NUMBER,AGENCY, BANK, TYPE_ACCOUNT ) VALUES (60, '40', '40', 'CONTA_CREDITO');